server:
  port: 9090




spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:

      httpclient:
        pool:
          type: fixed
          max-connections: 1000
          acquire-timeout: 7500
          max-idle-time: 90s
          max-life-time: 90s
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - HEAD
              - OPTIONS
              - PUT
            allowedHeaders:
              - "*"
              - "Authorization"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      routes:
        - id: BUSSERVICE
          uri: lb://BUSSERVICE
          predicates:
            - Path=/api/v1/buses/**
          filters:
            - AuthenticationFilter


        - id: BUSSCHEDULE
          uri: lb://BUSSCHEDULE
          predicates:
            - Path=/api/v1/schedules/**
          filters:
            - AuthenticationFilter


        - id: BUSBOOKING
          uri: lb://BUSBOOKING
          predicates:
            - Path=/api/v1/bookings/**
          filters:
            - AuthenticationFilter

        - id: IDENTITY-SERVICE
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE